In [9]:
from fastai.data.all import *
from fastai.vision.all import *

In [2]:
path = untar_data(URLs.PETS)
path

Path('/home/jithin/.fastai/data/oxford-iiit-pet')

In [3]:
fnames = get_image_files(path/'images')

In [4]:
dblock = DataBlock()
dsets = dblock.datasets(fnames)
dsets.train[0]

(Path('/home/jithin/.fastai/data/oxford-iiit-pet/images/Birman_151.jpg'),
 Path('/home/jithin/.fastai/data/oxford-iiit-pet/images/Birman_151.jpg'))

In [5]:
def label_func(fname):
    return "cat" if fname.name[0].isupper() else "dog"

In [4]:
import numpy as np

In [3]:
np.ones([1, 5], dtype=np.float32)

array([[1., 1., 1., 1., 1.]], dtype=float32)

In [13]:
dblock = DataBlock(get_items = lambda x: np.ones([5, 5], np.float32), 
                   get_y = lambda x: np.sum(x))

In [14]:
dsets = dblock.datasets(None)
dsets.train[3]

(array([1., 1., 1., 1., 1.], dtype=float32), 5.0)

In [15]:
import torch.nn as nn
import torch

class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()
        self.fc = nn.Linear(5, 1, bias=False)
        torch.nn.init.ones_(self.fc.weight)
        
    def forward(self, x):
        x = self.fc(x)
        return x

In [16]:
dsets[0][0].dtype

dtype('float32')

In [17]:
dl = torch.utils.data.DataLoader(dsets, batch_size=4)
model = TestModel()

In [18]:
model(torch.Tensor(dsets[0][0]))

tensor([5.], grad_fn=<SqueezeBackward3>)

In [19]:
dls = dsets.dataloaders()

In [20]:
dls.items

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [12]:
loss = CrossEntropyLossFlat()

In [21]:
learner = Learner(dls, model, loss)

In [18]:
dsets[0][0]

array([1., 1., 1., 1., 1.], dtype=float32)

In [22]:
learner.predict(dsets[0][0])


(tensor([5.]), tensor([5.]), tensor([5.]))

In [77]:
loss.activation = lambda x: x

In [10]:
class DummyLoss(Module):
    reduction = 'none'
    def forward(self, x, y): return x
    def activation(self, x): return x
    def decodes(self, x): return x
    
loss = DummyLoss()

In [24]:
from fastai.torch_core import Module

In [23]:
learner.export()

PicklingError: Can't pickle <function <lambda> at 0x7f8049f045f0>: attribute lookup <lambda> on __main__ failed

In [27]:
dir(fastai)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'basics',
 'callback',
 'data',
 'fp16_utils',
 'imports',
 'interpret',
 'layers',
 'learner',
 'losses',
 'metrics',
 'optimizer',
 'torch_basics',
 'torch_core',
 'torch_imports',
 'vision']

In [1]:
from fastai.data.block import DataBlock